# Generated by Django 3.0.6 on 2020-06-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20200602_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='de_ferias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
